name: Publish Docker images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"
  push:
    tags:
      - "v*"
env:
  REGISTRY_IMAGE: testesscn/teslamate

permissions:
  contents: read
  packages: write

jobs:
  teslamate_build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "linux/amd64"
            runs_on: "ubuntu-latest"
            cache_id: amd64
          - platform: "linux/arm/v7"
            runs_on: "buildjet-2vcpu-ubuntu-2204-arm"
            cache_id: arm
          - platform: "linux/arm64"
            runs_on: "buildjet-2vcpu-ubuntu-2204-arm"
            cache_id: arm64

    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Buildx
        uses: ./.github/actions/build
        with:
          is_dockerhub_pushed: "1"
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.ref_name }}

  teslamate_merge:
    runs-on: ubuntu-latest
    needs:
      - teslamate_build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: testesscn
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: ./.github/actions/merge
        with:
          image: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule,pattern=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=edge
  grafana:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: testesscn
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: ./.github/actions/grafana
        with:
          tags: |
            type=edge
            type=schedule,pattern=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
